apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: superapp-broker-knp-dev
  labels:
    strimzi.io/cluster: superapp-cluster-dev
spec:
  replicas: 1
  roles:
    - broker
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 500m
  jvmOptions:
    -Xms: 256m
    -Xmx: 512m
  storage:
    type: persistent-claim
    size: 1Gi
    deleteClaim: true